### ISSUE TITLE
Defaults to port 51254, even if set differently in config

### ISSUE THREAD

**Issue by agricolab** [labstreaminglayer/App-BrainProducts#3]
The initial configuration sets the port to 51244, and the GUI starts showing this port in the text field. Yet, when i start the GUI and press link immediatly, it tries to connect with port 51254. If i play with the selection menu, and set it to 51244, it connects with this port.

**Comment by dmedine** [comment]
Yes, this is a bit buggy. I rushed to get it out. I might have some time to get this right in the next few days, but as far as I know, it doesn't work with RecView anyway.

**Comment by agricolab** [comment]
It still works if i workaround, so no hurry. Let me take the opportunity to express how much i like how markers are now synced with the EEG. Thanks!

**Comment by dmedine** [comment]
I just rebuilt this and it worked fine. Then, I downloaded the latest releases for both x64 and x86 and they both worked fine as well. I looked at the source code and I can't find any reason for it to behave this way either.

I'm going to keep this open because I seem to remember this happening earlier when I was playing around with this, but as of today (31.07.2019) I can't recreate this bug.

You're welcome for the EEG/marker sync ;-)

**Comment by agricolab** [comment]
I took a look at the source code. The only feasible origin of this bug is when the config file is loaded in line 83 during start-up, as it defaults to 51244 in line 32, and setting via the GUI works. I put the 51244 in ```brainvision_config.cfg``` into quotes. It works now. Additionally, i can reproduce the bug if i remove the quotes. 
```
<?xml version="1.0" encoding="utf-8"?>
<settings><serverip>127.0.0.1</serverip><port>"51244"</port></settings>
```
Don't know why it already worked on your machine. Maybe this is another issue with locale or OS. I run Labrecorder on Win10 with english locale.
